### ISSUE TITLE
您好，请问论文中的气管数据集可以提供下载吗，谢谢

### ISSUE THREAD

**Issue by y8421036** [haozheng-sjtu/Local-imbalance-based-Weight#1]

**Comment by haozheng-sjtu** [comment]
Labels have been uploaded, see 3d-airway-segmentation/BAS.rar.

**Comment by y8421036** [comment]
> Labels have been uploaded, see 3d-airway-segmentation/BAS.rar.

Thank you very much! Have a nice life!
