### ISSUE TITLE
A confusing about the LIB weight 

### ISSUE THREAD

**Issue by yono-liu** [haozheng-sjtu/Local-imbalance-based-Weight#2]
您好，郑师兄，非常感谢您能上传代码为开源作出贡献。
我有一个问题关于文章里的Local-imbalance-based-Weight。在文章里Weight的权重是
![image](https://user-images.githubusercontent.com/56424072/183846010-8734d1f0-92d1-4cf2-8279-c1ca59f95f2f.png)
但是在代码里，

`weight = weight**np.random.random(2,3) * label + (1-label)`

问题是，为什么是乘以`label`，而不是乘以λ。以及原文里的函数f_c是
![image](https://user-images.githubusercontent.com/56424072/183846715-f44d683a-bfe2-4a91-887c-1c17813af260.png)
在代码里也没有体现出来呢。
还是说您上传的代码只是用于测试阶段呢，感谢！

**Comment by haozheng-sjtu** [comment]
非常感谢指出这个问题！因为训练的时候采用的是varied weighted training，求权重的这一段应该是写到dataloader里的，而不是像demo里这样提前求出来存好。dataloader里按照文章里的公式就好，这一段只是简单的演示~

**Comment by yono-liu** [comment]
感谢师兄的回复！
我明白师兄的意思了，师兄您介意上传更完整的代码版本吗。我还是有些地方有些困惑，比如说
这个随机是每一个epoch随机一次，还是对每一个case都随机一次呢，以及
最后就是直接用对每个case产生的weight代替General Union Loss 里面的weight项吗。
感谢

**Comment by haozheng-sjtu** [comment]
每个epoch都变，直接用在loss里。除了权重部分其他的都和3D-airway-segmentation里的代码一致。

**Comment by yono-liu** [comment]
谢谢师兄！
